development: &development  
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development  
production: &production  
  :url:      redis://h:p5005c37d4e4d1282a8f6a40d54d5f768ece48a2803e6e11da664cae59817ae8b@ec2-18-214-19-12.compute-1.amazonaws.com:51089
  :host: c2-18-214-19-12.compute-1.amazonaws.com
  :port: 51089
  :password: 349f93483fv9erfv849dfvdfbds9
  :inline: true
  :timeout: 1